server:
  port: ${env.APPLICATION_PORT:8081}
  servlet:
    context-path: /api/v1

application:
  title: Recipe Sharing
  version: 1.0.0

spring:
  application:
    name: recipe-sharing
  flyway:
    enable: true
    baseline-on-migrate: false
    locations: classpath:db/migration
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${env.DB_PASSWORD}
    url: jdbc:postgresql://${env.DB_HOST}:${env.DB_PORT}/${env.DB_NAME}
    username: ${env.DB_USER:postgres}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

spring-doc:
  api-docs:
    path: /api-docs
    resolve-schema-properties: true
    write-yaml: true
  swagger-ui:
    disable-swagger-default-url: true

jwt:
  secret: h9G+QWz3G7u0Rk5+Q3YzN9Kz+zN5R3F5zYQw3zN6Q1Z3Qk5yW3L0==

management:
  server:
    port: ${env.MANAGEMENT_PORT:9091}
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always